# SL lattice with M-point (π,π) ordering

dim = 2

a0 = [ 1.0, 0.0 ]
a1 = [ 0.0, 1.0 ]

A0 = [ 1, -1 ]
A1 = [ 1, 1 ]

num_sub = 1
pos_sub0 = [ 0.0, 0.0 ]

[[sub0]]
site = [ 0, 0 ]
[[sub0]]
site = [ 1, 0 ]

