# TL lattice with K-point ordering

dim = 2

a0 = [ 1.0, 0.0 ]
a1 = [ -0.5, 0.86602540378443865 ]

A0 = [ 2, 1 ]
A1 = [ 1, 2 ]

num_sub = 1
pos_sub0 = [ 0.0, 0.0 ]

[[sub0]]
site = [ 0, 0 ]
[[sub0]]
site = [ 1, 0 ]
[[sub0]]
site = [ 1, 1 ]

